server:
  port: 8081

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxxxx
    url: jdbc:mysql://localhost:3306/bank
    password: xxxxxxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  logging.level.org.springframework.web: DEBUG

